version: '3.6'
services:
  db:
    environment:
      - MYSQL_DATABASE=hackernews
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=apizilla
      - MYSQL_PASSWORD=root
    command:
      - --table_definition_cache=100
      - --performance_schema=0
      - --default-authentication-plugin=mysql_native_password
      - --innodb_use_native_aio=0
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./tmp/mysql-data:/var/lib/mysql
    container_name: apizilla-mysql
    image: mysql

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./tmp/rabbit/:/var/lib/rabbitmq/
      - ./tmp/rabbit-log/:/var/log/rabbitmq

  apizilla-hackernews:
    environment:
      HACKER_NEWS_SQL_DNS: "root:root@tcp(db:3306)/hackernews?parseTime=true"
    container_name: hackernews
    ports:
      - 8080:8080
    build:
      dockerfile: ./Dockerfile
      context: ./
    volumes:
      - ./:/etc/apizilla/
    depends_on:
      - rabbitmq
      - db
